import IncidenceTheory.FoundationIncidenceWitness
import IncidenceTheory.FoundationCompletion
import IncidenceTheory.ReferenceFoundationConservativity
import IncidenceTheory.CompletionCapstone
import IncidenceTheory.ReferenceFoundationMetatheory
import IncidenceTheory.ReferenceFoundationKripke
import IncidenceTheory.ReferenceFoundationInfinity
import IncidenceTheory.ReferenceFoundationCanonical
import IncidenceTheory.ReferenceFoundationZFModel
import IncidenceTheory.ReferenceFoundationEncoding
import IncidenceTheory.ReferenceFoundationLindenbaum
import IncidenceTheory.ReferenceFoundationLayeredCanonical
import IncidenceTheory.IncidenceResearch
import IncidenceTheory.DependentCompletedComprehensionNaturality
import IncidenceTheory.DependentWholeCwFMorphismReadiness
import IncidenceTheory.DependentDisplayProjectionSemantics
import IncidenceTheory.DependentSemanticSubstitutionComposition
import IncidenceTheory.DependentSemanticPairingRealization
import IncidenceTheory.DependentGeneralSemanticPairing
import IncidenceTheory.DependentRawSubstitutionDecomposition
import IncidenceTheory.DependentSemanticSubstitutionInduction
import IncidenceTheory.DependentCoherentSemanticSubstitution
import IncidenceTheory.DependentCoherentSemanticSubstitutionClosure
import IncidenceTheory.DependentCoherentWholeCwFReadiness
import IncidenceTheory.DependentCoherentSemanticSubstitutionInduction
import IncidenceTheory.DependentAlignedContextSemantics
import IncidenceTheory.DependentSourceHeadSemanticCoverage
import IncidenceTheory.DependentTwoSidedCoherentSemanticSubstitution
import IncidenceTheory.DependentSourceHeadReadinessAlignment
import IncidenceTheory.DependentGlobalTwoSidedSubstitutionCoverage
import IncidenceTheory.DependentFormationTargetInvariance
import IncidenceTheory.DependentMutualTargetInvarianceMotive
import IncidenceTheory.DependentFormationConstructorTargetEquations
import IncidenceTheory.DependentFormationTargetPackage
import IncidenceTheory.DependentPiSigmaTargetInvariance
import IncidenceTheory.DependentIdentityTargetPackage
import IncidenceTheory.DependentCanonicalRebase
import IncidenceTheory.DependentDispatcherTargetInvariance
import IncidenceTheory.DependentScopedTargetInvarianceBase
import IncidenceTheory.DependentScopedPiSigmaTargetInvariance
import IncidenceTheory.DependentScopedTypingTargetInvarianceBase
import IncidenceTheory.DependentScopedIdentityTargetInvariance
import IncidenceTheory.DependentScopedFormationTargetInvariance
import IncidenceTheory.DependentScopedLambdaTargetInvariance
import IncidenceTheory.DependentScopedReflTargetInvariance
import IncidenceTheory.DependentScopedApplyTargetInvariance

open IncidenceCore
open IncidenceCore.ReferenceFoundation
open IncidenceCore.ReferenceFoundation.IncProof

#print axioms derives_sound
#print axioms IncDepCompletionModel.interpretTyping_sound
#print axioms hfReferenceFoundation_consistent
#print axioms hfReferenceIncidenceWitness_nontrivial
#print axioms encode_derivation_sound
#print axioms encode_conservative
#print axioms conservativeIncExtension
#print axioms finiteFoundationCertificate
#print axioms finiteFoundation_preserves_and_reflects
#print axioms Derives.weaken_prefix
#print axioms Derives.cut
#print axioms Derives.substitute
#print axioms KripkeStructure.force_monotone
#print axioms KripkeStructure.derives_sound
#print axioms actualInfinity_is_not_finite_placeholder
#print axioms Canonical.truth
#print axioms Canonical.complete_of_countermodels
#print axioms zfActualInfinityModel
#print axioms zfActualInfinityFoundation_consistent
#print axioms formulaAt_surjective
#print axioms exists_maximalAvoiding
#print axioms MaximalAvoiding.or_iff
#print axioms PrimeTheory.imp_iff
#print axioms LayeredPrimeTheory.future_counterexample_of_imp_not_mem
#print axioms LayeredPrimeTheory.future_counterexample_of_all_not_mem
#print axioms LayeredCanonical.truth
#print axioms LayeredCanonical.countermodel_of_not_derives
#print axioms LayeredCanonical.complete
#print axioms referenceFoundation_kripke_complete
#print axioms completeFoundationCertificate
#print axioms incidenceTheoryPaperCapstone
#print axioms incDepRawFiniteCwFTheorem
#print axioms incDepCompletedCwFComparisonTheorem
#print axioms incDepCompletedSubstitutionNaturalityTheorem
#print axioms incDepCompletedComprehensionNaturalityTheorem
#print axioms incDepWholeCwFMorphismBoundaryTheorem
#print axioms incDepCompletedDisplayProjectionSemanticsTheorem
#print axioms incDepSemanticSubstitutionCompositionTheorem
#print axioms incDepSemanticPairingRealizationTheorem
#print axioms incDepGeneralSemanticPairingTheorem
#print axioms incDepRawSubstitutionDecompositionTheorem
#print axioms incDepSemanticSubstitutionInductionTheorem
#print axioms incDepCoherentSemanticSubstitutionTheorem
#print axioms incDepCoherentSemanticSubstitutionClosureTheorem
#print axioms incDepCoherentWholeCwFMorphismBoundaryTheorem
#print axioms incDepCoherentSemanticSubstitutionInductionTheorem
#print axioms incDepAlignedContextSemanticsTheorem
#print axioms incDepSourceHeadSemanticCoverageBoundaryTheorem
#print axioms incDepTwoSidedCoherentSemanticSubstitutionTheorem
#print axioms incDepSourceHeadReadinessAlignmentTheorem
#print axioms incDepGlobalTwoSidedSubstitutionCoverageTheorem
#print axioms incDepFormationTargetInvarianceBoundaryTheorem
#print axioms incDepMutualTargetInvarianceMotiveTheorem
#print axioms incDepFormationConstructorTargetEquationsTheorem
#print axioms incDepFormationTargetPackageTheorem
#print axioms incDepPiSigmaTargetInvarianceTheorem
#print axioms incDepIdentityTargetPackageTheorem
#print axioms incDepCanonicalRebaseTheorem
#print axioms incDepDispatcherTargetInvarianceTheorem
#print axioms incDepScopedTargetInvarianceBaseTheorem
#print axioms incDepScopedPiSigmaTargetInvarianceTheorem
#print axioms incDepScopedTypingTargetInvarianceBaseTheorem
#print axioms incDepScopedCanonicalTyping_formation_eq
#print axioms IncDepRawStrictTypingSubstitutionDispatchResult.targetTermCast_heq
#print axioms incDepScopedIdentityTargetInvarianceTheorem
#print axioms incDepScopedFormationTargetInvarianceTheorem
#print axioms incDepScopedTypingRecursiveNormalizationTheorem
#print axioms incDepScopedLambdaTargetInvarianceTheorem
#print axioms incDepScopedReflTargetInvarianceTheorem
#print axioms incDepScopedApplyTargetPackageTheorem
#print axioms incDepScopedApplyRecursiveInstantiationTargetCoherence
#print axioms incDepScopedApplyInstantiationTargetCoherence
